export const languages = [
  { label: 'Arabic', value: 'ar' },
  { label: 'German', value: 'de' },
  { label: 'English', value: 'en' },
  { label: 'Spanish', value: 'es' },
  { label: 'French', value: 'fr' },
  { label: 'Italian', value: 'it' },
  { label: 'Dutch', value: 'nl' },
  { label: 'Norwegian', value: 'no' },
  { label: 'Portuguese', value: 'pt' },
  { label: 'Russian', value: 'ru' }
];

export const countries = [
  { label: 'United Arab Emirates', value: 'ae' },
  { label: 'Argentina', value: 'ar' },
  { label: 'Austria', value: 'at' },
  { label: 'Australia', value: 'au' },
  { label: 'Belgium', value: 'be' },
  { label: 'Bulgaria', value: 'bg' },
  { label: 'Brazil', value: 'br' },
  { label: 'Canada', value: 'ca' },
  { label: 'China', value: 'cn' },
  { label: 'Colombia', value: 'co' },
  { label: 'Cuba', value: 'cu' },
  { label: 'Czech Republic', value: 'cz' },
  { label: 'Germany', value: 'de' },
  { label: 'Egypt', value: 'eg' },
  { label: 'France', value: 'fr' },
  { label: 'United Kingdom', value: 'GB' },
  { label: 'Hong Kong', value: 'hk' },
  { label: 'Hungary', value: 'hu' },
  { label: '  Indonesia', value: 'id' },
  { label: 'Ireland', value: 'ie' },
  { label: 'Israel', value: 'il' },
  { label: 'Italy', value: 'it' },
  { label: 'India', value: 'in' },
  { label: 'Japan', value: 'jp' },
  { label: 'Korea, Republic of', value: 'kr' },
  { label: 'Lithuania', value: 'lt' },
  { label: 'Latvia', value: 'lv' },
  { label: 'Morocco', value: 'ma' },
  { label: 'Mexico', value: 'mx' },
  { label: 'Malaysia', value: 'my' },
  { label: 'Nigeria', value: 'ng' },
  { label: 'Netherlands', value: 'nl' },
  { label: 'Norway', value: 'no' },
  { label: 'New Zealand', value: 'nz' },
  { label: 'Philippines', value: 'ph' },
  { label: 'Poland', value: 'pl' },
  { label: 'Portugal', value: 'pt' },
  { label: 'Romania', value: 'ro' },
  { label: 'Russian Federation', value: 'ru' },
  { label: 'Saudi Arabia', value: 'sa' },
  { label: 'Sweden', value: 'se' },
  { label: 'Singapore', value: 'sg' },
  { label: 'Slovenia', value: 'si' },
  { label: 'Slovakia', value: 'sk' },
  { label: 'Thailand', value: 'th' },
  { label: 'Turkey', value: 'tr' },
  { label: 'Taiwan, Province of China', value: 'tw' },
  { label: 'Ukraine', value: 'ua' },
  { label: 'United States', value: 'us' },
  { label: 'Venezuela', value: 've' },
  { label: 'South Africa', value: 'za' }
];

export const categories = [
  { label: 'business', value: 'business' },
  { label: 'general', value: 'general' },
  { label: 'entertainment', value: 'entertainment' },
  { label: 'health', value: 'health' },
  { label: 'science', value: 'science' },
  { label: 'sports', value: 'sports' },
  { label: 'technology', value:	'technology'}
];